# Generated by Django 5.2.15 on 2026-06-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('OPTION', 'Option')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Type-specific config: {min, max} for numeric types; {options: [...]} for OPTION.')),
                ('is_system', models.BooleanField(default=False, help_text='System trackers are seeded defaults and cannot be deleted.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Inactive trackers are hidden but values are kept.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_values', to='journal.entry')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='trackers.tracker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_tracker_key_per_user'),
        ),
        migrations.AddConstraint(
            model_name='trackervalue',
            constraint=models.UniqueConstraint(fields=('entry', 'tracker'), name='unique_value_per_entry_tracker'),
        ),
    ]
