# Generated by Django 5.2.15 on 2026-06-16 21:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_pg_trgm'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='Maintained by post_save signal; never set directly.', null=True),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='entry_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='entry_title_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body'], name='entry_body_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
